import type { Destination } from "./types";

/**
 * Realistic London-area sample data for Demo Mode.
 * Image URLs are public Unsplash photos — no API keys required.
 */
export const DEMO_DESTINATIONS: Destination[] = [
  {
    id: "quiet-grounds",
    name: "Quiet Grounds",
    category: "Café",
    imageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    rating: 4.8,
    reviewCount: 612,
    distanceMiles: 0.6,
    travelMinutes: 8,
    parkingScore: 94,
    priceLevel: 2,
    isOpen: true,
    closesAt: "9:00 PM",
    tags: ["Quiet", "Wi-Fi", "Outdoor Seating", "Free Parking", "Laptop-Friendly"],
    coordinates: { lat: 51.5122, lng: -0.1312 },
    aiExplanation:
      "Quiet atmosphere, free parking, outdoor seating, excellent Wi-Fi, only 8 minutes away.",
    parking: [
      {
        id: "qg-garage",
        name: "Bedford Garage",
        type: "garage",
        walkingMinutes: 3,
        walkingMeters: 180,
        estimatedCost: "£2.40 / hr",
        hasEvCharging: true,
        accessible: true,
        score: 96,
        coordinates: { lat: 51.5116, lng: -0.1324 },
      },
      {
        id: "qg-street",
        name: "Monmouth St (pay & display)",
        type: "street",
        walkingMinutes: 2,
        walkingMeters: 110,
        estimatedCost: "£1.80 / hr",
        hasEvCharging: false,
        accessible: false,
        score: 78,
        coordinates: { lat: 51.5125, lng: -0.1304 },
      },
    ],
    signals: {
      reviewQuality: 94,
      valueScore: 82,
      amenityCoverage: 96,
    },
  },
  {
    id: "harbor-light",
    name: "Harbor Light Sushi",
    category: "Sushi",
    imageUrl:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80",
    rating: 4.6,
    reviewCount: 890,
    distanceMiles: 1.1,
    travelMinutes: 14,
    parkingScore: 71,
    priceLevel: 2,
    isOpen: true,
    closesAt: "10:30 PM",
    tags: ["Great Value", "Accessible", "Reservations"],
    coordinates: { lat: 51.5074, lng: -0.1278 },
    aiExplanation:
      "Consistently strong reviews under £20, solid parking options, open now — great sushi pick nearby.",
    parking: [
      {
        id: "hl-garage",
        name: "Trafalgar Car Park",
        type: "garage",
        walkingMinutes: 5,
        walkingMeters: 320,
        estimatedCost: "£3.20 / hr",
        hasEvCharging: true,
        accessible: true,
        score: 74,
        coordinates: { lat: 51.5082, lng: -0.1291 },
      },
      {
        id: "hl-street",
        name: "Strand side bays",
        type: "street",
        walkingMinutes: 4,
        walkingMeters: 240,
        estimatedCost: "£2.60 / hr",
        hasEvCharging: false,
        accessible: true,
        score: 62,
        coordinates: { lat: 51.5069, lng: -0.1265 },
      },
    ],
    signals: {
      reviewQuality: 88,
      valueScore: 91,
      amenityCoverage: 68,
    },
  },
  {
    id: "terrace-co",
    name: "Terrace & Co",
    category: "Brunch Café",
    imageUrl:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    rating: 4.7,
    reviewCount: 445,
    distanceMiles: 0.9,
    travelMinutes: 11,
    parkingScore: 88,
    priceLevel: 2,
    isOpen: true,
    closesAt: "4:00 PM",
    tags: ["Outdoor Seating", "Brunch", "Wi-Fi", "Pet Friendly", "Free Parking"],
    coordinates: { lat: 51.5155, lng: -0.141 },
    aiExplanation:
      "Sunny terrace, easy parking, and brunch menus that match weekend demand — ideal outdoor pick.",
    parking: [
      {
        id: "tc-lot",
        name: "Soho Square Lot",
        type: "lot",
        walkingMinutes: 2,
        walkingMeters: 140,
        estimatedCost: "£2.00 / hr",
        hasEvCharging: false,
        accessible: true,
        score: 90,
        coordinates: { lat: 51.5151, lng: -0.142 },
      },
      {
        id: "tc-street",
        name: "Greek Street bays",
        type: "street",
        walkingMinutes: 3,
        walkingMeters: 190,
        estimatedCost: "£1.90 / hr",
        hasEvCharging: false,
        accessible: false,
        score: 72,
        coordinates: { lat: 51.516, lng: -0.1402 },
      },
    ],
    signals: {
      reviewQuality: 90,
      valueScore: 78,
      amenityCoverage: 86,
    },
  },
  {
    id: "night-owl",
    name: "Night Owl Coffee",
    category: "Café",
    imageUrl:
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
    rating: 4.5,
    reviewCount: 328,
    distanceMiles: 1.4,
    travelMinutes: 16,
    parkingScore: 66,
    priceLevel: 1,
    isOpen: true,
    closesAt: "1:00 AM",
    tags: ["Late Night", "Laptop-Friendly", "Wi-Fi", "Quiet", "Great Value"],
    coordinates: { lat: 51.5202, lng: -0.12 },
    aiExplanation:
      "Open late with calm corners and strong Wi-Fi — built for deep work after hours.",
    parking: [
      {
        id: "no-garage",
        name: "Brunswick Centre Garage",
        type: "garage",
        walkingMinutes: 6,
        walkingMeters: 400,
        estimatedCost: "£2.80 / hr",
        hasEvCharging: true,
        accessible: true,
        score: 70,
        coordinates: { lat: 51.524, lng: -0.1235 },
      },
      {
        id: "no-street",
        name: "Marchmont Street",
        type: "street",
        walkingMinutes: 3,
        walkingMeters: 200,
        estimatedCost: "£1.50 / hr",
        hasEvCharging: false,
        accessible: false,
        score: 58,
        coordinates: { lat: 51.5196, lng: -0.119 },
      },
    ],
    signals: {
      reviewQuality: 84,
      valueScore: 93,
      amenityCoverage: 80,
    },
  },
  {
    id: "ember-roast",
    name: "Ember Roast",
    category: "Coffee Shop",
    imageUrl:
      "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    rating: 4.4,
    reviewCount: 210,
    distanceMiles: 0.4,
    travelMinutes: 6,
    parkingScore: 58,
    priceLevel: 2,
    isOpen: true,
    closesAt: "6:00 PM",
    tags: ["Outdoor Seating", "Wi-Fi", "Great Value"],
    coordinates: { lat: 51.5138, lng: -0.1355 },
    aiExplanation:
      "Closest outdoor coffee option — quick walk, solid reviews, lighter on parking.",
    parking: [
      {
        id: "er-street",
        name: "Shaftesbury Ave bays",
        type: "street",
        walkingMinutes: 4,
        walkingMeters: 260,
        estimatedCost: "£2.20 / hr",
        hasEvCharging: false,
        accessible: false,
        score: 55,
        coordinates: { lat: 51.5129, lng: -0.134 },
      },
      {
        id: "er-garage",
        name: "China Town NCP",
        type: "garage",
        walkingMinutes: 7,
        walkingMeters: 480,
        estimatedCost: "£3.50 / hr",
        hasEvCharging: true,
        accessible: true,
        score: 64,
        coordinates: { lat: 51.5115, lng: -0.1318 },
      },
    ],
    signals: {
      reviewQuality: 80,
      valueScore: 85,
      amenityCoverage: 62,
    },
  },
];
